/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LABGUI;

import LABBLL.LABBoletaBLL;
import LABDAL.LABClienteDAL;
import javax.swing.JOptionPane;
import LABBLL.LABCliente;
import LABDAL.LABBoletaDAL;
import LABDAL.LABConectarDAL;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alega
 */
public class LABBoleta extends javax.swing.JFrame {

    /**
     * Creates new form LABBoleta
     */
    public LABBoleta() {
        initComponents();
        this.setTitle("Modulo Venta");
        this.setSize(555, 649);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
         
        this.txtErroConexion.setVisible(false);
        this.txtToalPagar.setVisible(false);
        this. txtIDBOleta.setVisible(false);
        this.txtIdCliente.setVisible(false);
        this.txtNombreCliente.setVisible(false);
        this.txtApellidoCLiente.setVisible(false);
        this.txtCorreo.setVisible(false);
        this.txtSaldo.setVisible(false);
        this.txtIdCliente.setVisible(false);
        this.jLabel7.setVisible(false);
        
         try 
         {
             
       LABBoletaDAL per = new LABBoletaDAL();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id Detalle Boleta");
        modelo.addColumn("Pruducto");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        
        for(LABBoletaBLL p : per.mostrarDetalleBoleta(Integer.parseInt("0")))
        {
            Object[] fila = new Object[12];
            
            fila[0] = p.getId_boleta();
            fila[1] = p.getProducto();
            fila[2] = p.getPrecio();  
            fila[3] = p.getCantidad();  
             
            modelo.addRow(fila);
        }
        LABBoleta.jTable1.setModel(modelo);
         } 
         
         catch (Exception e) 
         {
            JOptionPane.showMessageDialog(null, "erro al generar ...");
         } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtRutCLiente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JLabel();
        txtApellidoCLiente = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        btnSeleccioarProducto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtToalPagar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDBOleta = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtErroConexion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Venta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        btnBuscarCliente.setText("Buscar CLiente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel8.setText("Correo");

        jLabel9.setText("Saldo");

        txtRutCLiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutCLienteActionPerformed(evt);
            }
        });
        txtRutCLiente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRutCLienteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRutCLienteKeyTyped(evt);
            }
        });

        txtNombreCliente.setText("S/D");

        txtApellidoCLiente.setText("S/D");

        txtCorreo.setText("S/D");

        txtSaldo.setText("S/D");

        jLabel7.setText("ID:");

        txtIdCliente.setText("jLabel11");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRutCLiente))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtApellidoCLiente))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreCliente)))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdCliente)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtSaldo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtCorreo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarCliente)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtIdCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNombreCliente)
                            .addComponent(jLabel8)
                            .addComponent(txtCorreo))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRutCLiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoCLiente)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(txtSaldo))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Thour"));
        jPanel5.setForeground(new java.awt.Color(255, 255, 204));

        btnSeleccioarProducto.setText("Selecionar Tour");
        btnSeleccioarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccioarProductoActionPerformed(evt);
            }
        });

        jLabel2.setText("Monto a Pagar");

        txtToalPagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtToalPagar.setForeground(new java.awt.Color(255, 102, 102));
        txtToalPagar.setText("0");

        jLabel3.setText("Numero Boleta");

        txtIDBOleta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtIDBOleta.setForeground(new java.awt.Color(0, 51, 255));
        txtIDBOleta.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtToalPagar)
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtIDBOleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSeleccioarProducto)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccioarProducto)
                    .addComponent(jLabel2)
                    .addComponent(txtToalPagar)
                    .addComponent(jLabel3)
                    .addComponent(txtIDBOleta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtErroConexion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtErroConexion.setForeground(new java.awt.Color(255, 51, 51));
        txtErroConexion.setText("Error en conexion...");

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Boleta"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setText("Pagar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar Venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton3)
                        .addGap(33, 33, 33)
                        .addComponent(txtErroConexion)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtErroConexion)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
        LABMenuGUI menucliente = new LABMenuGUI();
       menucliente.setLocationRelativeTo(null);
       menucliente.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
    try{
            LABClienteDAL client = new LABClienteDAL();
            LABCliente   cli  = new LABCliente();
            cli = client.buscarCliente(this.txtRutCLiente.getText());
            if (cli.getEstado()==1) {
                this.txtNombreCliente.setText(cli.getNombre());
                this.txtApellidoCLiente.setText(cli.getApellido());
                this.txtCorreo.setText((cli.getCorreo()));
                this.txtSaldo.setText(String.valueOf(cli.getSaldo()));
                this.txtIdCliente.setText(String.valueOf(cli.getId_cliente()));

              this.txtNombreCliente.setVisible(true);
              this.txtApellidoCLiente.setVisible(true);
              this.txtCorreo.setVisible(true);
              this.txtSaldo.setVisible(true);
              
            }else{
                JOptionPane.showMessageDialog(null, "El Rut no esta Registrado", "RUT NO REGISTRADO", JOptionPane.WARNING_MESSAGE);
       this.txtNombreCliente.setVisible(false);
        this.txtApellidoCLiente.setVisible(false);
        this.txtCorreo.setVisible(false);
        this.txtSaldo.setVisible(false);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error al buscar rut");

        }
             
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnSeleccioarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccioarProductoActionPerformed
        
        LABBoletaBLL co = new LABBoletaBLL();
        LABClienteDAL cli = new LABClienteDAL();
        
        try 
        {
            if( this.txtRutCLiente.getText().length() > 0)
            {
                co.setId_cliente(Integer.parseInt(txtIdCliente.getText())); 
                cli.agregarBoleta(co);
                co=cli.ultimaBoleta(txtIdCliente.getText());
                
                String res = String.valueOf(co.getId_boleta()); 
                this.txtIDBOleta.setText(res);
                this.txtIDBOleta.setVisible(true);
                LABGUI.LABProducto menu = new LABGUI.LABProducto();
                menu.setVisible(true);
                LABProducto.idBoleta2.setText(this.txtIDBOleta.getText()); 
            
            }else JOptionPane.showMessageDialog(null, "debe seleccionar un cliente");
        
        } 
        
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(null, "error en la conexion");
        }
 
        
        
        
    }//GEN-LAST:event_btnSeleccioarProductoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
   int v1= Integer.parseInt(this.txtSaldo.getText());     
   int v2= Integer.parseInt(this.txtToalPagar.getText());      
   
   
    if ( v1 >= v2) 
        {
            int nuevoMonto=0;
            nuevoMonto=v1-v2;
            
           LABBoletaDAL  co = new LABBoletaDAL ();
           LABBoletaBLL c = new LABBoletaBLL(); 
           
           c.setId_boleta(Integer.parseInt(txtIDBOleta.getText()));
           c.setId_cliente(Integer.parseInt(txtIdCliente.getText()));
           c.setSaldo(nuevoMonto);
           co.actualizaBoletaPagada(c);
           co.descuentoPago(c);
           JOptionPane.showMessageDialog(null, "Pago realizado"); 
           LABBoleta.btnSeleccioarProducto.setEnabled(true);
           this.txtRutCLiente.setText("");
           this.txtToalPagar.setText("");
           this.txtIDBOleta.setText("");
           this.txtNombreCliente.setText("");
           this.txtApellidoCLiente.setText("");
           this.txtCorreo.setText("");
           this.txtSaldo.setText("");
           this.txtIdCliente.setText("");
           try 
         {
             
       LABBoletaDAL per = new LABBoletaDAL();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id Detalle Boleta");
        modelo.addColumn("Pruducto");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        
        for(LABBoletaBLL p : per.mostrarDetalleBoleta(Integer.parseInt("0")))
        {
            Object[] fila = new Object[12];
            
            fila[0] = p.getId_boleta();
            fila[1] = p.getProducto();
            fila[2] = p.getPrecio();  
            fila[3] = p.getCantidad();  
             
            modelo.addRow(fila);
        }
        LABBoleta.jTable1.setModel(modelo);
         } 
         
         catch (Exception e) 
         {
            JOptionPane.showMessageDialog(null, "erro al generar ...");
         } 
           
           
        }   else JOptionPane.showMessageDialog(null, "Salado insuficiente"); 
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       LABBoleta.btnSeleccioarProducto.setEnabled(true);
       this.txtRutCLiente.setText("");
       this.txtToalPagar.setText("");
       this.txtIDBOleta.setText("");
       this.txtIDBOleta.setVisible(false);
       this.txtToalPagar.setVisible(false);
       this.txtNombreCliente.setText("");
       this.txtApellidoCLiente.setText("");
       this.txtCorreo.setText("");
       this.txtSaldo.setText("");
       this.txtIdCliente.setText("");
       
        try 
         {
             
       LABBoletaDAL per = new LABBoletaDAL();
        
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id Detalle Boleta");
        modelo.addColumn("Pruducto");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        
        for(LABBoletaBLL p : per.mostrarDetalleBoleta(Integer.parseInt("0")))
        {
            Object[] fila = new Object[12];
            
            fila[0] = p.getId_boleta();
            fila[1] = p.getProducto();
            fila[2] = p.getPrecio();  
            fila[3] = p.getCantidad();  
             
            modelo.addRow(fila);
        }
        LABBoleta.jTable1.setModel(modelo);
         } 
         
         catch (Exception e) 
         {
            JOptionPane.showMessageDialog(null, "erro al generar ...");
         } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtRutCLienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutCLienteKeyPressed
        if(evt.getKeyCode()==524){
            System.out.println("Press Inicio");
            evt.consume();
        }
        
        
    }//GEN-LAST:event_txtRutCLienteKeyPressed

    private void txtRutCLienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRutCLienteKeyTyped

        
        
        
        
        
    }//GEN-LAST:event_txtRutCLienteKeyTyped

    private void txtRutCLienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutCLienteActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutCLienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LABBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LABBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LABBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LABBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LABBoleta().setVisible(true);
            }
          }
       );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    public static javax.swing.JButton btnSeleccioarProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JLabel txtApellidoCLiente;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtErroConexion;
    public static javax.swing.JLabel txtIDBOleta;
    private javax.swing.JLabel txtIdCliente;
    private javax.swing.JLabel txtNombreCliente;
    private javax.swing.JTextField txtRutCLiente;
    public static javax.swing.JLabel txtSaldo;
    public static javax.swing.JLabel txtToalPagar;
    // End of variables declaration//GEN-END:variables
}
