/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LABGUI;

import LABBLL.LABCliente;
import LABDAL.LABClienteDAL;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author alega
 */
public class LABClienteGUI extends javax.swing.JFrame {

    /**
     * Creates new form LABCliente
     */
    public LABClienteGUI() {
        initComponents();
        //Datos del Jframe----//
        this.setTitle("Administrador Clientes");
        this.setSize(685, 649);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setIconImage(new ImageIcon(getClass().getResource("/LABImagenes/icons8-usuario-40.png")).getImage());
        //---------Datos Tabla Mostrar-------------//
        LABClienteDAL client = new LABClienteDAL();
        for(LABCliente cl : client.mostrarCliente())
        {
            Object[] fila = new Object[5];
            fila[0] = client.FormatoRutUsuario(cl.getRun()+cl.getDv());
            fila[1] = cl.getNombre();
            fila[2] = cl.getApellido();
            fila[3] = cl.getCorreo();
            fila[4] = cl.getSaldo();
          ((DefaultTableModel)tablamcliente.getModel()).addRow(fila);
        }
       
        
        
        //ocultar paneles y botones //
      this.panelauxacusuario.setVisible(false);
      this.panelauxeusuario.setVisible(false);
      this.panelauxesaldo.setVisible(false);
      panelauxrecargausuario.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtdvausuario = new javax.swing.JTextField();
        txtrutagregarusuario = new javax.swing.JTextField();
        txtsaldoausuario = new javax.swing.JTextField();
        txtcorreoausuario = new javax.swing.JTextField();
        txtapellidoausuario = new javax.swing.JTextField();
        txtnombreausuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtrutacusuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnbuscaracusuario = new javax.swing.JButton();
        panelauxacusuario = new javax.swing.JPanel();
        txtcorreoacusuario = new javax.swing.JTextField();
        txtapellidoacusuario = new javax.swing.JTextField();
        txtnombreacusuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnacusuario = new javax.swing.JButton();
        checkacusuario = new javax.swing.JCheckBox();
        btnsalir1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtruteusuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnbuscareusuario = new javax.swing.JButton();
        checkeusuario = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        panelauxeusuario = new javax.swing.JPanel();
        txtcorreoeusuario = new javax.swing.JTextField();
        txtapellidoeusuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btneusuario = new javax.swing.JButton();
        txtnombreeusuario = new javax.swing.JTextField();
        btnsalir2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablamcliente = new javax.swing.JTable();
        btnimprimir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnsalir4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtrutsaldousuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnbuscarrecargausuario = new javax.swing.JButton();
        checkrecargausuario = new javax.swing.JCheckBox();
        panelauxrecargausuario = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtcorreorecargausuario = new javax.swing.JTextField();
        txtapellidorecargausuario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnrecargarusuario = new javax.swing.JButton();
        txtnombrerecargausuario = new javax.swing.JTextField();
        txtrecargausuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnsalir3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtrutesaldousuario = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnbuscaresaldo = new javax.swing.JButton();
        checkesaldousuario = new javax.swing.JCheckBox();
        panelauxesaldo = new javax.swing.JPanel();
        txtcorreesaldo = new javax.swing.JTextField();
        txtapellidoesaldo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btnrecargarusuario1 = new javax.swing.JButton();
        txtnombreesaldo = new javax.swing.JTextField();
        btnsalir5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(58, 145, 187));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(58, 145, 187));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(58, 145, 187));
        jLabel1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Cliente");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 40, 300, 50);

        txtdvausuario.setBackground(new java.awt.Color(255, 255, 255));
        txtdvausuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtdvausuario.setForeground(new java.awt.Color(58, 145, 187));
        txtdvausuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdvausuario.setText("DV");
        txtdvausuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdvausuarioMouseClicked(evt);
            }
        });
        txtdvausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdvausuarioActionPerformed(evt);
            }
        });
        txtdvausuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdvausuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtdvausuario);
        txtdvausuario.setBounds(420, 250, 40, 30);

        txtrutagregarusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtrutagregarusuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtrutagregarusuario.setForeground(new java.awt.Color(58, 145, 187));
        txtrutagregarusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtrutagregarusuario.setText("RUT");
        txtrutagregarusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtrutagregarusuarioMouseClicked(evt);
            }
        });
        txtrutagregarusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutagregarusuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtrutagregarusuario);
        txtrutagregarusuario.setBounds(210, 250, 190, 30);

        txtsaldoausuario.setBackground(new java.awt.Color(255, 255, 255));
        txtsaldoausuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtsaldoausuario.setForeground(new java.awt.Color(58, 145, 187));
        txtsaldoausuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsaldoausuario.setText("Saldo");
        txtsaldoausuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsaldoausuarioMouseClicked(evt);
            }
        });
        txtsaldoausuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsaldoausuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtsaldoausuario);
        txtsaldoausuario.setBounds(270, 370, 160, 30);

        txtcorreoausuario.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreoausuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcorreoausuario.setForeground(new java.awt.Color(58, 145, 187));
        txtcorreoausuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcorreoausuario.setText("Correo");
        txtcorreoausuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcorreoausuarioMouseClicked(evt);
            }
        });
        jPanel1.add(txtcorreoausuario);
        txtcorreoausuario.setBounds(210, 310, 260, 30);

        txtapellidoausuario.setBackground(new java.awt.Color(255, 255, 255));
        txtapellidoausuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtapellidoausuario.setForeground(new java.awt.Color(58, 145, 187));
        txtapellidoausuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtapellidoausuario.setText("Apellidos");
        txtapellidoausuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtapellidoausuarioMouseClicked(evt);
            }
        });
        jPanel1.add(txtapellidoausuario);
        txtapellidoausuario.setBounds(350, 190, 230, 30);

        txtnombreausuario.setBackground(new java.awt.Color(255, 255, 255));
        txtnombreausuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtnombreausuario.setForeground(new java.awt.Color(58, 145, 187));
        txtnombreausuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombreausuario.setText("Nombres");
        txtnombreausuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnombreausuarioMouseClicked(evt);
            }
        });
        jPanel1.add(txtnombreausuario);
        txtnombreausuario.setBounds(100, 190, 230, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(400, 240, 20, 40);

        btnsalir.setBackground(new java.awt.Color(58, 145, 187));
        btnsalir.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-cancelar-40.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalir);
        btnsalir.setBounds(490, 510, 46, 60);

        btnguardar.setBackground(new java.awt.Color(58, 145, 187));
        btnguardar.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-guardar-40.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnguardar);
        btnguardar.setBounds(430, 510, 52, 60);

        jTabbedPane1.addTab("Agregar", new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-añadir-usuario-masculino-16.png")), jPanel1, "Agregar Cliente"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(58, 145, 187));
        jPanel2.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(58, 145, 187));
        jLabel3.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Actualizar Cliente");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(170, 20, 330, 50);

        txtrutacusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtrutacusuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtrutacusuario.setForeground(new java.awt.Color(58, 145, 187));
        txtrutacusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtrutacusuario.setText("RUT");
        txtrutacusuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtrutacusuarioCaretUpdate(evt);
            }
        });
        txtrutacusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtrutacusuarioMouseClicked(evt);
            }
        });
        txtrutacusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutacusuarioKeyTyped(evt);
            }
        });
        jPanel2.add(txtrutacusuario);
        txtrutacusuario.setBounds(220, 140, 190, 30);

        jLabel7.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ingresa el Rut del Cliente");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(230, 110, 220, 22);

        btnbuscaracusuario.setBackground(new java.awt.Color(58, 145, 187));
        btnbuscaracusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-encuentra-hombre-usuario-22.png"))); // NOI18N
        btnbuscaracusuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnbuscaracusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscaracusuarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscaracusuario);
        btnbuscaracusuario.setBounds(410, 140, 40, 30);

        panelauxacusuario.setBackground(new java.awt.Color(58, 145, 187));
        panelauxacusuario.setLayout(null);

        txtcorreoacusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreoacusuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcorreoacusuario.setForeground(new java.awt.Color(58, 145, 187));
        txtcorreoacusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcorreoacusuario.setText("Correo");
        txtcorreoacusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcorreoacusuarioMouseClicked(evt);
            }
        });
        panelauxacusuario.add(txtcorreoacusuario);
        txtcorreoacusuario.setBounds(0, 170, 270, 30);

        txtapellidoacusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtapellidoacusuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtapellidoacusuario.setForeground(new java.awt.Color(58, 145, 187));
        txtapellidoacusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtapellidoacusuario.setText("Apellidos");
        txtapellidoacusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtapellidoacusuarioMouseClicked(evt);
            }
        });
        panelauxacusuario.add(txtapellidoacusuario);
        txtapellidoacusuario.setBounds(20, 110, 220, 30);

        txtnombreacusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtnombreacusuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtnombreacusuario.setForeground(new java.awt.Color(58, 145, 187));
        txtnombreacusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombreacusuario.setText("Nombres");
        txtnombreacusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnombreacusuarioMouseClicked(evt);
            }
        });
        panelauxacusuario.add(txtnombreacusuario);
        txtnombreacusuario.setBounds(20, 60, 220, 30);

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Modifique Los Datos del CLiente");
        panelauxacusuario.add(jLabel8);
        jLabel8.setBounds(20, 20, 220, 17);

        btnacusuario.setBackground(new java.awt.Color(58, 145, 187));
        btnacusuario.setForeground(new java.awt.Color(255, 255, 255));
        btnacusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-editar-40.png"))); // NOI18N
        btnacusuario.setText("Actualizar");
        btnacusuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnacusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnacusuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnacusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacusuarioActionPerformed(evt);
            }
        });
        panelauxacusuario.add(btnacusuario);
        btnacusuario.setBounds(200, 310, 63, 60);

        jPanel2.add(panelauxacusuario);
        panelauxacusuario.setBounds(210, 200, 270, 390);

        checkacusuario.setBackground(new java.awt.Color(58, 145, 187));
        checkacusuario.setForeground(new java.awt.Color(51, 255, 51));
        jPanel2.add(checkacusuario);
        checkacusuario.setBounds(190, 140, 30, 30);

        btnsalir1.setBackground(new java.awt.Color(58, 145, 187));
        btnsalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-cancelar-40.png"))); // NOI18N
        btnsalir1.setText("Salir");
        btnsalir1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalir1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnsalir1);
        btnsalir1.setBounds(490, 510, 46, 60);

        jTabbedPane1.addTab("Actualizar", new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-editar-usuario-masculino-16.png")), jPanel2, "Actualizar Cliente"); // NOI18N

        jPanel3.setBackground(new java.awt.Color(58, 145, 187));
        jPanel3.setLayout(null);

        txtruteusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtruteusuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtruteusuario.setForeground(new java.awt.Color(58, 145, 187));
        txtruteusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtruteusuario.setText("RUT");
        txtruteusuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtruteusuarioCaretUpdate(evt);
            }
        });
        txtruteusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtruteusuarioMouseClicked(evt);
            }
        });
        txtruteusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtruteusuarioKeyTyped(evt);
            }
        });
        jPanel3.add(txtruteusuario);
        txtruteusuario.setBounds(220, 140, 190, 30);

        jLabel9.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingresa el Rut del Cliente");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(230, 110, 220, 22);

        btnbuscareusuario.setBackground(new java.awt.Color(58, 145, 187));
        btnbuscareusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-encuentra-hombre-usuario-22.png"))); // NOI18N
        btnbuscareusuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnbuscareusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscareusuarioActionPerformed(evt);
            }
        });
        jPanel3.add(btnbuscareusuario);
        btnbuscareusuario.setBounds(410, 140, 40, 30);

        checkeusuario.setBackground(new java.awt.Color(58, 145, 187));
        checkeusuario.setForeground(new java.awt.Color(51, 255, 51));
        jPanel3.add(checkeusuario);
        checkeusuario.setBounds(190, 140, 30, 30);

        jLabel4.setBackground(new java.awt.Color(58, 145, 187));
        jLabel4.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Eliminar Cliente");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(190, 30, 300, 50);

        panelauxeusuario.setBackground(new java.awt.Color(58, 145, 187));
        panelauxeusuario.setLayout(null);

        txtcorreoeusuario.setEditable(false);
        txtcorreoeusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreoeusuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcorreoeusuario.setForeground(new java.awt.Color(58, 145, 187));
        txtcorreoeusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcorreoeusuario.setText("Correo");
        txtcorreoeusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcorreoeusuarioMouseClicked(evt);
            }
        });
        panelauxeusuario.add(txtcorreoeusuario);
        txtcorreoeusuario.setBounds(0, 160, 290, 30);

        txtapellidoeusuario.setEditable(false);
        txtapellidoeusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtapellidoeusuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtapellidoeusuario.setForeground(new java.awt.Color(58, 145, 187));
        txtapellidoeusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtapellidoeusuario.setText("Apellidos");
        txtapellidoeusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtapellidoeusuarioMouseClicked(evt);
            }
        });
        panelauxeusuario.add(txtapellidoeusuario);
        txtapellidoeusuario.setBounds(30, 100, 220, 30);

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Datos Cliente");
        panelauxeusuario.add(jLabel10);
        jLabel10.setBounds(70, 20, 120, 20);

        btneusuario.setBackground(new java.awt.Color(58, 145, 187));
        btneusuario.setForeground(new java.awt.Color(255, 255, 255));
        btneusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-eliminar-40.png"))); // NOI18N
        btneusuario.setText("Eliminar");
        btneusuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btneusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneusuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneusuarioActionPerformed(evt);
            }
        });
        panelauxeusuario.add(btneusuario);
        btneusuario.setBounds(240, 310, 52, 60);

        txtnombreeusuario.setEditable(false);
        txtnombreeusuario.setBackground(new java.awt.Color(255, 255, 255));
        txtnombreeusuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtnombreeusuario.setForeground(new java.awt.Color(58, 145, 187));
        txtnombreeusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombreeusuario.setText("Nombres");
        txtnombreeusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnombreeusuarioMouseClicked(evt);
            }
        });
        panelauxeusuario.add(txtnombreeusuario);
        txtnombreeusuario.setBounds(30, 50, 220, 30);

        jPanel3.add(panelauxeusuario);
        panelauxeusuario.setBounds(190, 200, 300, 390);

        btnsalir2.setBackground(new java.awt.Color(58, 145, 187));
        btnsalir2.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-cancelar-40.png"))); // NOI18N
        btnsalir2.setText("Salir");
        btnsalir2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalir2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnsalir2);
        btnsalir2.setBounds(500, 510, 46, 60);

        jTabbedPane1.addTab("Eliminar", new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-retire-hombre-usuario-16.png")), jPanel3, "Eliminar cliente"); // NOI18N

        jPanel4.setBackground(new java.awt.Color(58, 145, 187));
        jPanel4.setLayout(null);

        jLabel5.setBackground(new java.awt.Color(58, 145, 187));
        jLabel5.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mostrar Clientes");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(130, 10, 300, 50);

        tablamcliente.setBackground(new java.awt.Color(58, 145, 187));
        tablamcliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tablamcliente.setForeground(new java.awt.Color(255, 255, 255));
        tablamcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RUT", "Nombre", "Apellido", "Correo", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablamcliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablamcliente.setGridColor(new java.awt.Color(58, 145, 187));
        tablamcliente.setName(""); // NOI18N
        tablamcliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablamcliente);
        if (tablamcliente.getColumnModel().getColumnCount() > 0) {
            tablamcliente.getColumnModel().getColumn(0).setResizable(false);
            tablamcliente.getColumnModel().getColumn(0).setPreferredWidth(90);
            tablamcliente.getColumnModel().getColumn(1).setMinWidth(153);
            tablamcliente.getColumnModel().getColumn(1).setPreferredWidth(153);
            tablamcliente.getColumnModel().getColumn(1).setMaxWidth(153);
            tablamcliente.getColumnModel().getColumn(2).setMinWidth(153);
            tablamcliente.getColumnModel().getColumn(2).setPreferredWidth(153);
            tablamcliente.getColumnModel().getColumn(2).setMaxWidth(153);
            tablamcliente.getColumnModel().getColumn(3).setMinWidth(185);
            tablamcliente.getColumnModel().getColumn(3).setPreferredWidth(185);
            tablamcliente.getColumnModel().getColumn(3).setMaxWidth(185);
            tablamcliente.getColumnModel().getColumn(4).setMinWidth(75);
            tablamcliente.getColumnModel().getColumn(4).setPreferredWidth(75);
            tablamcliente.getColumnModel().getColumn(4).setMaxWidth(75);
        }

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 660, 460);

        btnimprimir.setBackground(new java.awt.Color(58, 145, 187));
        btnimprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-enviar-a-la-impresora-40.png"))); // NOI18N
        btnimprimir.setText("Imprimir");
        btnimprimir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnimprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnimprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnimprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimprimirActionPerformed(evt);
            }
        });
        jPanel4.add(btnimprimir);
        btnimprimir.setBounds(430, 530, 70, 60);

        jButton1.setBackground(new java.awt.Color(58, 145, 187));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-cambiar-usuario-masculino-40.png"))); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(520, 530, 70, 60);

        btnsalir4.setBackground(new java.awt.Color(58, 145, 187));
        btnsalir4.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-cancelar-40.png"))); // NOI18N
        btnsalir4.setText("Salir");
        btnsalir4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsalir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalir4ActionPerformed(evt);
            }
        });
        jPanel4.add(btnsalir4);
        btnsalir4.setBounds(610, 530, 46, 60);

        jTabbedPane1.addTab("Mostrar", new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-encuentra-hombre-usuario-16.png")), jPanel4, "Mostrar clientes y saldo "); // NOI18N

        jPanel5.setBackground(new java.awt.Color(58, 145, 187));
        jPanel5.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(58, 145, 187));
        jLabel6.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Recargar Saldo");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(190, 50, 300, 50);

        txtrutsaldousuario.setBackground(new java.awt.Color(255, 255, 255));
        txtrutsaldousuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtrutsaldousuario.setForeground(new java.awt.Color(58, 145, 187));
        txtrutsaldousuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtrutsaldousuario.setText("RUT");
        txtrutsaldousuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtrutsaldousuarioCaretUpdate(evt);
            }
        });
        txtrutsaldousuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtrutsaldousuarioMouseClicked(evt);
            }
        });
        txtrutsaldousuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutsaldousuarioKeyTyped(evt);
            }
        });
        jPanel5.add(txtrutsaldousuario);
        txtrutsaldousuario.setBounds(230, 160, 190, 30);

        jLabel11.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ingresa el Rut del Cliente");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(240, 130, 220, 22);

        btnbuscarrecargausuario.setBackground(new java.awt.Color(58, 145, 187));
        btnbuscarrecargausuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-encuentra-hombre-usuario-22.png"))); // NOI18N
        btnbuscarrecargausuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnbuscarrecargausuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarrecargausuarioActionPerformed(evt);
            }
        });
        jPanel5.add(btnbuscarrecargausuario);
        btnbuscarrecargausuario.setBounds(420, 160, 40, 30);

        checkrecargausuario.setBackground(new java.awt.Color(58, 145, 187));
        checkrecargausuario.setForeground(new java.awt.Color(51, 255, 51));
        jPanel5.add(checkrecargausuario);
        checkrecargausuario.setBounds(200, 160, 30, 30);

        panelauxrecargausuario.setBackground(new java.awt.Color(58, 145, 187));
        panelauxrecargausuario.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("$");
        panelauxrecargausuario.add(jLabel14);
        jLabel14.setBounds(80, 240, 20, 30);

        txtcorreorecargausuario.setEditable(false);
        txtcorreorecargausuario.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreorecargausuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcorreorecargausuario.setForeground(new java.awt.Color(58, 145, 187));
        txtcorreorecargausuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcorreorecargausuario.setText("Correo");
        txtcorreorecargausuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcorreorecargausuarioMouseClicked(evt);
            }
        });
        panelauxrecargausuario.add(txtcorreorecargausuario);
        txtcorreorecargausuario.setBounds(30, 160, 270, 30);

        txtapellidorecargausuario.setEditable(false);
        txtapellidorecargausuario.setBackground(new java.awt.Color(255, 255, 255));
        txtapellidorecargausuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtapellidorecargausuario.setForeground(new java.awt.Color(58, 145, 187));
        txtapellidorecargausuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtapellidorecargausuario.setText("Apellidos");
        txtapellidorecargausuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtapellidorecargausuarioMouseClicked(evt);
            }
        });
        panelauxrecargausuario.add(txtapellidorecargausuario);
        txtapellidorecargausuario.setBounds(50, 100, 220, 30);

        jLabel12.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Datos Cliente");
        panelauxrecargausuario.add(jLabel12);
        jLabel12.setBounds(100, 20, 120, 20);

        btnrecargarusuario.setBackground(new java.awt.Color(58, 145, 187));
        btnrecargarusuario.setForeground(new java.awt.Color(255, 255, 255));
        btnrecargarusuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-donar-40.png"))); // NOI18N
        btnrecargarusuario.setText("Recargar");
        btnrecargarusuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnrecargarusuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnrecargarusuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnrecargarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecargarusuarioActionPerformed(evt);
            }
        });
        panelauxrecargausuario.add(btnrecargarusuario);
        btnrecargarusuario.setBounds(232, 290, 60, 60);

        txtnombrerecargausuario.setEditable(false);
        txtnombrerecargausuario.setBackground(new java.awt.Color(255, 255, 255));
        txtnombrerecargausuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtnombrerecargausuario.setForeground(new java.awt.Color(58, 145, 187));
        txtnombrerecargausuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombrerecargausuario.setText("Nombres");
        txtnombrerecargausuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnombrerecargausuarioMouseClicked(evt);
            }
        });
        panelauxrecargausuario.add(txtnombrerecargausuario);
        txtnombrerecargausuario.setBounds(50, 50, 220, 30);

        txtrecargausuario.setBackground(new java.awt.Color(255, 255, 255));
        txtrecargausuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtrecargausuario.setForeground(new java.awt.Color(58, 145, 187));
        txtrecargausuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtrecargausuario.setText("ej: 1000");
        txtrecargausuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtrecargausuarioMouseClicked(evt);
            }
        });
        txtrecargausuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrecargausuarioKeyTyped(evt);
            }
        });
        panelauxrecargausuario.add(txtrecargausuario);
        txtrecargausuario.setBounds(100, 240, 150, 30);

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ingresa el monto de Recarga");
        panelauxrecargausuario.add(jLabel13);
        jLabel13.setBounds(70, 210, 210, 30);

        jPanel5.add(panelauxrecargausuario);
        panelauxrecargausuario.setBounds(180, 220, 310, 350);

        btnsalir3.setBackground(new java.awt.Color(58, 145, 187));
        btnsalir3.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-cancelar-40.png"))); // NOI18N
        btnsalir3.setText("Salir");
        btnsalir3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalir3ActionPerformed(evt);
            }
        });
        jPanel5.add(btnsalir3);
        btnsalir3.setBounds(500, 510, 46, 60);

        jTabbedPane1.addTab("Recarga Saldo", new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-monedas-16.png")), jPanel5, "Recarga Saldo cliente"); // NOI18N

        jPanel6.setBackground(new java.awt.Color(58, 145, 187));
        jPanel6.setLayout(null);

        jLabel15.setBackground(new java.awt.Color(58, 145, 187));
        jLabel15.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Eliminar Saldo");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(190, 50, 300, 50);

        txtrutesaldousuario.setBackground(new java.awt.Color(255, 255, 255));
        txtrutesaldousuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtrutesaldousuario.setForeground(new java.awt.Color(58, 145, 187));
        txtrutesaldousuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtrutesaldousuario.setText("RUT");
        txtrutesaldousuario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtrutesaldousuarioCaretUpdate(evt);
            }
        });
        txtrutesaldousuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtrutesaldousuarioMouseClicked(evt);
            }
        });
        txtrutesaldousuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrutesaldousuarioKeyTyped(evt);
            }
        });
        jPanel6.add(txtrutesaldousuario);
        txtrutesaldousuario.setBounds(230, 160, 190, 30);

        jLabel16.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ingresa el Rut del Cliente");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(240, 130, 220, 22);

        btnbuscaresaldo.setBackground(new java.awt.Color(58, 145, 187));
        btnbuscaresaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-encuentra-hombre-usuario-22.png"))); // NOI18N
        btnbuscaresaldo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnbuscaresaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscaresaldoActionPerformed(evt);
            }
        });
        btnbuscaresaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btnbuscaresaldoKeyTyped(evt);
            }
        });
        jPanel6.add(btnbuscaresaldo);
        btnbuscaresaldo.setBounds(420, 160, 40, 30);

        checkesaldousuario.setBackground(new java.awt.Color(58, 145, 187));
        checkesaldousuario.setForeground(new java.awt.Color(51, 255, 51));
        jPanel6.add(checkesaldousuario);
        checkesaldousuario.setBounds(200, 160, 30, 30);

        panelauxesaldo.setBackground(new java.awt.Color(58, 145, 187));
        panelauxesaldo.setLayout(null);

        txtcorreesaldo.setEditable(false);
        txtcorreesaldo.setBackground(new java.awt.Color(255, 255, 255));
        txtcorreesaldo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtcorreesaldo.setForeground(new java.awt.Color(58, 145, 187));
        txtcorreesaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcorreesaldo.setText("Correo");
        txtcorreesaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtcorreesaldoMouseClicked(evt);
            }
        });
        panelauxesaldo.add(txtcorreesaldo);
        txtcorreesaldo.setBounds(30, 200, 270, 30);

        txtapellidoesaldo.setEditable(false);
        txtapellidoesaldo.setBackground(new java.awt.Color(255, 255, 255));
        txtapellidoesaldo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtapellidoesaldo.setForeground(new java.awt.Color(58, 145, 187));
        txtapellidoesaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtapellidoesaldo.setText("Apellidos");
        txtapellidoesaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtapellidoesaldoMouseClicked(evt);
            }
        });
        panelauxesaldo.add(txtapellidoesaldo);
        txtapellidoesaldo.setBounds(50, 140, 220, 30);

        jLabel18.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Datos Cliente");
        panelauxesaldo.add(jLabel18);
        jLabel18.setBounds(100, 30, 120, 20);

        btnrecargarusuario1.setBackground(new java.awt.Color(58, 145, 187));
        btnrecargarusuario1.setForeground(new java.awt.Color(255, 255, 255));
        btnrecargarusuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-no-efectivo-16.png"))); // NOI18N
        btnrecargarusuario1.setText("Eliminar");
        btnrecargarusuario1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnrecargarusuario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnrecargarusuario1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnrecargarusuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrecargarusuario1ActionPerformed(evt);
            }
        });
        panelauxesaldo.add(btnrecargarusuario1);
        btnrecargarusuario1.setBounds(240, 280, 60, 60);

        txtnombreesaldo.setEditable(false);
        txtnombreesaldo.setBackground(new java.awt.Color(255, 255, 255));
        txtnombreesaldo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtnombreesaldo.setForeground(new java.awt.Color(58, 145, 187));
        txtnombreesaldo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnombreesaldo.setText("Nombres");
        txtnombreesaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnombreesaldoMouseClicked(evt);
            }
        });
        panelauxesaldo.add(txtnombreesaldo);
        txtnombreesaldo.setBounds(50, 80, 220, 30);

        jPanel6.add(panelauxesaldo);
        panelauxesaldo.setBounds(180, 230, 310, 350);

        btnsalir5.setBackground(new java.awt.Color(58, 145, 187));
        btnsalir5.setForeground(new java.awt.Color(255, 255, 255));
        btnsalir5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-cancelar-40.png"))); // NOI18N
        btnsalir5.setText("Salir");
        btnsalir5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsalir5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsalir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalir5ActionPerformed(evt);
            }
        });
        jPanel6.add(btnsalir5);
        btnsalir5.setBounds(500, 510, 46, 60);

        jTabbedPane1.addTab("Eliminar Saldo", new javax.swing.ImageIcon(getClass().getResource("/LABImagenes/icons8-no-efectivo-16.png")), jPanel6, "Eliminar saldo CLiente"); // NOI18N

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 690, 649);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
      try {
          if (client.validarRut(this.txtrutagregarusuario.getText()+this.txtdvausuario.getText())) {
             cl = client.buscarCliente(this.txtrutagregarusuario.getText());
              if (cl.getEstado()!=1) {
                  cl.setNombre(this.txtnombreausuario.getText());
                  cl.setApellido(this.txtapellidoausuario.getText());
                  cl.setRun(this.txtrutagregarusuario.getText());
                  cl.setDv(this.txtdvausuario.getText());
                  cl.setCorreo(this.txtcorreoausuario.getText());
                  cl.setSaldo(Integer.parseInt(this.txtsaldoausuario.getText()));
                  if (client.agregarCLiente(cl)==1) {
               JOptionPane.showMessageDialog(null, "Cliente Agregado exitosamente \n "+cl.toString(), "CLiente Agregado", JOptionPane.INFORMATION_MESSAGE);
               txtnombreausuario.setText("Nombres");
               txtapellidoausuario.setText("Apellidos");
               txtrutagregarusuario.setText("RUT");
               txtdvausuario.setText("DV");
               txtcorreoausuario.setText("Correo");
               txtsaldoausuario.setText("Saldo");
                  }else{
                    JOptionPane.showMessageDialog(null, "Cliente No Agregado", "Error: CLiente no Agregado", JOptionPane.WARNING_MESSAGE);   
                  }
              }else{
                   JOptionPane.showMessageDialog(null, "El Rut Ingresado ya se encuentra Registrado ", " ERROR: RUT Ya Ingresado", JOptionPane.WARNING_MESSAGE);
              }
          }else{
               JOptionPane.showMessageDialog(null, "Ingrese un rut valido", "RUT Invalido", JOptionPane.WARNING_MESSAGE);
          }
            
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Verifique el Texto Ingresado", "Error al Registrar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtdvausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdvausuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdvausuarioActionPerformed

    private void txtnombreausuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreausuarioMouseClicked
        this.txtnombreausuario.setText("");
    }//GEN-LAST:event_txtnombreausuarioMouseClicked

    private void txtapellidoausuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidoausuarioMouseClicked
        this.txtapellidoausuario.setText("");
    }//GEN-LAST:event_txtapellidoausuarioMouseClicked

    private void txtrutagregarusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrutagregarusuarioMouseClicked
        this.txtrutagregarusuario.setText("");
    }//GEN-LAST:event_txtrutagregarusuarioMouseClicked

    private void txtdvausuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdvausuarioMouseClicked
       txtdvausuario.setText("");
    }//GEN-LAST:event_txtdvausuarioMouseClicked

    private void txtcorreoausuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreoausuarioMouseClicked
       txtcorreoausuario.setText("");
    }//GEN-LAST:event_txtcorreoausuarioMouseClicked

    private void txtsaldoausuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsaldoausuarioMouseClicked
        txtsaldoausuario.setText("");
    }//GEN-LAST:event_txtsaldoausuarioMouseClicked

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        dispose();
        LABMenuGUI menucliente = new LABMenuGUI();
       menucliente.setLocationRelativeTo(null);
       menucliente.setVisible(true);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtrutacusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrutacusuarioMouseClicked
        this.txtrutacusuario.setText("");
        this.panelauxacusuario.setVisible(false);
        this.checkacusuario.setSelected(false);
        this.txtrutacusuario.setEditable(true);
    }//GEN-LAST:event_txtrutacusuarioMouseClicked

    private void txtnombreacusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreacusuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreacusuarioMouseClicked

    private void txtapellidoacusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidoacusuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoacusuarioMouseClicked

    private void txtcorreoacusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreoacusuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoacusuarioMouseClicked

    private void btnsalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalir1ActionPerformed
        this.panelauxacusuario.setVisible(false);
        this.txtrutacusuario.setEditable(true);
        dispose();
        LABMenuGUI menucliente = new LABMenuGUI();
       menucliente.setLocationRelativeTo(null);
       menucliente.setVisible(true);
    }//GEN-LAST:event_btnsalir1ActionPerformed

    private void txtrutacusuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtrutacusuarioCaretUpdate
       LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
        try {
            cl = client.buscarCliente(this.txtrutacusuario.getText());
            if (cl.getEstado()==1) {
                this.checkacusuario.setSelected(true);
            }else{
                this.checkacusuario.setSelected(false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtrutacusuarioCaretUpdate

    private void btnbuscaracusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscaracusuarioActionPerformed
       LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
        try {
            cl = client.buscarCliente(this.txtrutacusuario.getText());
            if (cl.getEstado()==1) {
               //seteo datos //
               this.txtnombreacusuario.setText(cl.getNombre());
               this.txtapellidoacusuario.setText(cl.getApellido());
               this.txtcorreoacusuario.setText(cl.getCorreo());
               //----Muestro el panel--------//
               this.panelauxacusuario.setVisible(true);
               this.txtrutacusuario.setEditable(false);
               }else{
         JOptionPane.showMessageDialog(null, "El Rut no se encuentra registrado", "RUT No Encontrado", JOptionPane.WARNING_MESSAGE);
                this.panelauxacusuario.setVisible(false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnbuscaracusuarioActionPerformed

    private void btnacusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacusuarioActionPerformed
        LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
        try {
            cl = client.buscarCliente(this.txtrutacusuario.getText());
            cl.setNombre(this.txtnombreacusuario.getText());
            cl.setApellido(this.txtapellidoacusuario.getText());
            cl.setCorreo(this.txtcorreoacusuario.getText());
            //Sentencia if //
            if (client.actualizarCliente(cl)==1) {
            cl = client.buscarCliente(this.txtrutacusuario.getText());
       JOptionPane.showMessageDialog(null, "Cliente Actualizado exitosamente \n "+cl.toString(), "CLiente Actualizado", JOptionPane.INFORMATION_MESSAGE); 
            this.panelauxacusuario.setVisible(false);
            this.txtrutacusuario.setEditable(true);
            this.txtrutacusuario.setText("RUT");
           }else{
       JOptionPane.showMessageDialog(null, "Cliente no Actualizado", "Error: CLiente Actualizar", JOptionPane.WARNING_MESSAGE); 
                    }
            
        } catch (Exception e) {
              JOptionPane.showMessageDialog(null, "Verifique el Texto Ingresado", "Error al Actualizar", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnacusuarioActionPerformed

    private void txtrutacusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutacusuarioKeyTyped
       char c=evt.getKeyChar();
        if(txtrutacusuario.getText().length() >= 8){
            getToolkit().beep();
            evt.consume();
        }
        if (!Character.isDigit(c)) {
            evt.consume();
        }

        if(Character.isLetter(c))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtrutacusuarioKeyTyped

    private void txtrutagregarusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutagregarusuarioKeyTyped
       char c=evt.getKeyChar();
        if(txtrutagregarusuario.getText().length() >= 8){
            getToolkit().beep();
            evt.consume();
        }
        if (!Character.isDigit(c)) {
            evt.consume();
        }

        if(Character.isLetter(c))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtrutagregarusuarioKeyTyped

    private void txtdvausuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdvausuarioKeyTyped
       char c=evt.getKeyChar();
        String cad =(""+c).toUpperCase(); // en caso de K la transforma en Mayuscula//
        c=cad.charAt(0);
        evt.setKeyChar(c);
        if(txtdvausuario.getText().length() >= 1){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtdvausuarioKeyTyped

    private void txtsaldoausuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsaldoausuarioKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c) || this.txtsaldoausuario.getText().length() >= 9)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtsaldoausuarioKeyTyped

    private void txtruteusuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtruteusuarioCaretUpdate
        LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
        try {
            cl = client.buscarCliente(this.txtruteusuario.getText());
            if (cl.getEstado()==1) {
                this.checkeusuario.setSelected(true);
            }else{
                this.checkeusuario.setSelected(false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtruteusuarioCaretUpdate

    private void txtruteusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtruteusuarioMouseClicked
        this.txtruteusuario.setText("");
        this.panelauxeusuario.setVisible(false);
        this.checkeusuario.setSelected(false);
        
    }//GEN-LAST:event_txtruteusuarioMouseClicked

    private void txtruteusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtruteusuarioKeyTyped
         char c=evt.getKeyChar();
        if(txtruteusuario.getText().length() >= 8){
            getToolkit().beep();
            evt.consume();
        }
        if (!Character.isDigit(c)) {
            evt.consume();
        }

        if(Character.isLetter(c))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtruteusuarioKeyTyped

    private void btnbuscareusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscareusuarioActionPerformed
       LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
        try {
            cl = client.buscarCliente(this.txtruteusuario.getText());
            if (cl.getEstado()==1) {
               //seteo datos //
               this.txtnombreeusuario.setText(cl.getNombre());
               this.txtapellidoeusuario.setText(cl.getApellido());
               this.txtcorreoeusuario.setText(cl.getCorreo());
               //----Muestro el panel--------//
               this.panelauxeusuario.setVisible(true);
               }else{
         JOptionPane.showMessageDialog(null, "El Rut no se encuentra registrado", "RUT No Encontrado", JOptionPane.WARNING_MESSAGE);
                this.panelauxeusuario.setVisible(false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnbuscareusuarioActionPerformed

    private void btnsalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalir2ActionPerformed
        this.panelauxeusuario.setVisible(false);
         dispose();
       LABMenuGUI menucliente = new LABMenuGUI();
       menucliente.setLocationRelativeTo(null);
       menucliente.setVisible(true);
    }//GEN-LAST:event_btnsalir2ActionPerformed

    private void txtcorreoeusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreoeusuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoeusuarioMouseClicked

    private void txtapellidoeusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidoeusuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoeusuarioMouseClicked

    private void btneusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneusuarioActionPerformed
        LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
        try {
            if (JOptionPane.showConfirmDialog(null,"Eliminar Cliente","Estas Seguro ?",JOptionPane.YES_NO_OPTION,JOptionPane.ERROR_MESSAGE)==JOptionPane.YES_OPTION)
            {
            cl = client.buscarCliente(this.txtruteusuario.getText());
            //Sentencia if //
            if (client.desactivarCliente(cl)==1) {
       JOptionPane.showMessageDialog(null, "Cliente Eliminado exitosamente \n "+cl.toString(), "CLiente Eliminado", JOptionPane.INFORMATION_MESSAGE); 
            this.panelauxeusuario.setVisible(false);
            this.txtruteusuario.setText("RUT");
           }else{
       JOptionPane.showMessageDialog(null, "Cliente no Eliminado", "Error: CLiente Eliminar", JOptionPane.WARNING_MESSAGE); 
                    }
            }else{
                
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Veriffique el texto Ingresado");
        }
    }//GEN-LAST:event_btneusuarioActionPerformed

    private void txtnombreeusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreeusuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreeusuarioMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LABClienteDAL client = new LABClienteDAL();
        try {
             ((DefaultTableModel)tablamcliente.getModel()).setRowCount(0);
            for(LABCliente cl : client.mostrarCliente())
        {
            Object[] fila = new Object[5];
            fila[0] = client.FormatoRutUsuario(cl.getRun()+cl.getDv());
            fila[1] = cl.getNombre();
            fila[2] = cl.getApellido();
            fila[3] = cl.getCorreo();
            fila[4] = cl.getSaldo();
          ((DefaultTableModel)tablamcliente.getModel()).addRow(fila);
        }
          JOptionPane.showMessageDialog(null, "Lista Actualizada Correctamente \n Total : "+ ((DefaultTableModel)tablamcliente.getModel()).getRowCount()+" Registros", "Lista Actualizada", JOptionPane.INFORMATION_MESSAGE); 
            ((DefaultTableModel)tablamcliente.getModel()).getRowCount();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimprimirActionPerformed
        try {
            tablamcliente.print();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnimprimirActionPerformed

    private void txtrutsaldousuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtrutsaldousuarioCaretUpdate
        LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
        try {
            cl = client.buscarCliente(this.txtrutsaldousuario.getText());
            if (cl.getEstado()==1) {
                this.checkrecargausuario.setSelected(true);
            }else{
                this.checkrecargausuario.setSelected(false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtrutsaldousuarioCaretUpdate

    private void txtrutsaldousuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrutsaldousuarioMouseClicked
        this.txtrutsaldousuario.setText("");
        this.panelauxrecargausuario.setVisible(false);
        this.checkrecargausuario.setSelected(false);
    }//GEN-LAST:event_txtrutsaldousuarioMouseClicked

    private void txtrutsaldousuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutsaldousuarioKeyTyped
        char c=evt.getKeyChar();
        if(txtrutsaldousuario.getText().length() >= 8){
            getToolkit().beep();
            evt.consume();
        }
        if (!Character.isDigit(c)) {
            evt.consume();
        }

        if(Character.isLetter(c))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtrutsaldousuarioKeyTyped

    private void btnbuscarrecargausuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarrecargausuarioActionPerformed
         LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
        try {
            cl = client.buscarCliente(this.txtrutsaldousuario.getText());
            if (cl.getEstado()==1) {
               //seteo datos //
               this.txtnombrerecargausuario.setText(cl.getNombre());
               this.txtapellidorecargausuario.setText(cl.getApellido());
               this.txtcorreorecargausuario.setText(cl.getCorreo());
               this.txtrecargausuario.setText("ej: 1000");
               //----Muestro el panel--------//
               this.panelauxrecargausuario.setVisible(true);
               }else{
         JOptionPane.showMessageDialog(null, "El Rut no se encuentra registrado", "RUT No Encontrado", JOptionPane.WARNING_MESSAGE);
                this.panelauxrecargausuario.setVisible(false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnbuscarrecargausuarioActionPerformed

    private void btnsalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalir3ActionPerformed
        dispose();
        LABMenuGUI menucliente = new LABMenuGUI();
       menucliente.setLocationRelativeTo(null);
       menucliente.setVisible(true);
    }//GEN-LAST:event_btnsalir3ActionPerformed

    private void txtcorreorecargausuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreorecargausuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreorecargausuarioMouseClicked

    private void txtapellidorecargausuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidorecargausuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidorecargausuarioMouseClicked

    private void btnrecargarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecargarusuarioActionPerformed
        LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
        try {
           
            
       if (JOptionPane.showConfirmDialog(null,"Realizar Recarga","Estas Seguro ?",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.YES_OPTION)
            {
          cl =  client.buscarCliente(this.txtrutsaldousuario.getText());
          int recarga = Integer.parseInt(this.txtrecargausuario.getText());
            if (recarga >=100) {
                if (client.recargarSaldo(cl, recarga)==1) {
                cl =  client.buscarCliente(this.txtrutsaldousuario.getText());
       JOptionPane.showMessageDialog(null, "Recarga Realizada Correctamente \n  Su Nuevo Saldo es : "+cl.getSaldo(), "Recarga Exitosa", JOptionPane.INFORMATION_MESSAGE);
       this.panelauxrecargausuario.setVisible(false);
       this.txtrutsaldousuario.setText("RUT");
             }else{
                 JOptionPane.showMessageDialog(null, "Fallo al Realizar Recarga \n  Su Saldo es : "+cl.getSaldo(), "Recarga Erronea", JOptionPane.WARNING_MESSAGE);
            }
            }else{
               JOptionPane.showMessageDialog(null, "Monto Minimo de Recarga $ : 100 ", "Error al Recargar", JOptionPane.WARNING_MESSAGE);
               this.txtrecargausuario.setText("100"); 
            }
            }else{
           
       }
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verifique Texto", "Error al Recargar", JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_btnrecargarusuarioActionPerformed

    private void txtnombrerecargausuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombrerecargausuarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrerecargausuarioMouseClicked

    private void txtrecargausuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrecargausuarioMouseClicked
      this.txtrecargausuario.setText("");
    }//GEN-LAST:event_txtrecargausuarioMouseClicked

    private void txtrecargausuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrecargausuarioKeyTyped
    char c=evt.getKeyChar();
        if(Character.isLetter(c) || this.txtrecargausuario.getText().length() >= 9)
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtrecargausuarioKeyTyped

    private void btnsalir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalir4ActionPerformed
        dispose();
        LABMenuGUI menucliente = new LABMenuGUI();
       menucliente.setLocationRelativeTo(null);
       menucliente.setVisible(true);
    }//GEN-LAST:event_btnsalir4ActionPerformed

    private void txtrutesaldousuarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtrutesaldousuarioCaretUpdate
        LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
        try {
            cl = client.buscarCliente(this.txtrutesaldousuario.getText());
            if (cl.getEstado()==1) {
                this.checkesaldousuario.setSelected(true);
            }else{
                this.checkesaldousuario.setSelected(false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtrutesaldousuarioCaretUpdate

    private void txtrutesaldousuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtrutesaldousuarioMouseClicked
         this.txtrutesaldousuario.setText("");
        this.panelauxesaldo.setVisible(false);
        this.checkesaldousuario.setSelected(false);
    }//GEN-LAST:event_txtrutesaldousuarioMouseClicked

    private void txtrutesaldousuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrutesaldousuarioKeyTyped
       char c=evt.getKeyChar();
        if(txtrutesaldousuario.getText().length() >= 8){
            getToolkit().beep();
            evt.consume();
        }
        if (!Character.isDigit(c)) {
            evt.consume();
        }

        if(Character.isLetter(c))
        {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtrutesaldousuarioKeyTyped

    private void btnbuscaresaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscaresaldoActionPerformed
        LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
        try {
            cl = client.buscarCliente(this.txtrutesaldousuario.getText());
            if (cl.getEstado()==1) {
               //seteo datos //
               this.txtnombreesaldo.setText(cl.getNombre());
               this.txtapellidoesaldo.setText(cl.getApellido());
               this.txtcorreesaldo.setText(cl.getCorreo());
               //----Muestro el panel--------//
               this.panelauxesaldo.setVisible(true);
               }else{
         JOptionPane.showMessageDialog(null, "El Rut no se encuentra registrado", "RUT No Encontrado", JOptionPane.WARNING_MESSAGE);
                this.panelauxesaldo.setVisible(false);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnbuscaresaldoActionPerformed

    private void txtcorreesaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtcorreesaldoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreesaldoMouseClicked

    private void txtapellidoesaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtapellidoesaldoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoesaldoMouseClicked

    private void btnrecargarusuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrecargarusuario1ActionPerformed
       LABCliente cl = new LABCliente();
       LABClienteDAL client = new LABClienteDAL();
        try {
           
            
       if (JOptionPane.showConfirmDialog(null,"Eliminar Saldo","Estas Seguro ?",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE)==JOptionPane.YES_OPTION)
            {
          cl =  client.buscarCliente(this.txtrutesaldousuario.getText());
          client.eliminarSaldo(cl);
          cl = client.buscarCliente(this.txtrutesaldousuario.getText());
           JOptionPane.showMessageDialog(null, "Saldo Eliminado \n Nuevo Saldo : "+cl.getSaldo(), "Eliminar Saldo", JOptionPane.INFORMATION_MESSAGE);
           this.panelauxesaldo.setVisible(false);
           this.txtrutesaldousuario.setText("Rut");
           this.checkesaldousuario.setSelected(false);
            }else{
            
       }
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Verifique Texto", "Error al Recargar", JOptionPane.WARNING_MESSAGE);
            
        }       
    }//GEN-LAST:event_btnrecargarusuario1ActionPerformed

    private void txtnombreesaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnombreesaldoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreesaldoMouseClicked

    private void btnbuscaresaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnbuscaresaldoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscaresaldoKeyTyped

    private void btnsalir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalir5ActionPerformed
        dispose();
        LABMenuGUI menucliente = new LABMenuGUI();
       menucliente.setLocationRelativeTo(null);
       menucliente.setVisible(true);
    }//GEN-LAST:event_btnsalir5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LABClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LABClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LABClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LABClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LABClienteGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacusuario;
    private javax.swing.JButton btnbuscaracusuario;
    private javax.swing.JButton btnbuscaresaldo;
    private javax.swing.JButton btnbuscareusuario;
    private javax.swing.JButton btnbuscarrecargausuario;
    private javax.swing.JButton btneusuario;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnimprimir;
    private javax.swing.JButton btnrecargarusuario;
    private javax.swing.JButton btnrecargarusuario1;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnsalir1;
    private javax.swing.JButton btnsalir2;
    private javax.swing.JButton btnsalir3;
    private javax.swing.JButton btnsalir4;
    private javax.swing.JButton btnsalir5;
    private javax.swing.JCheckBox checkacusuario;
    private javax.swing.JCheckBox checkesaldousuario;
    private javax.swing.JCheckBox checkeusuario;
    private javax.swing.JCheckBox checkrecargausuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelauxacusuario;
    private javax.swing.JPanel panelauxesaldo;
    private javax.swing.JPanel panelauxeusuario;
    private javax.swing.JPanel panelauxrecargausuario;
    private javax.swing.JTable tablamcliente;
    private javax.swing.JTextField txtapellidoacusuario;
    private javax.swing.JTextField txtapellidoausuario;
    private javax.swing.JTextField txtapellidoesaldo;
    private javax.swing.JTextField txtapellidoeusuario;
    private javax.swing.JTextField txtapellidorecargausuario;
    private javax.swing.JTextField txtcorreesaldo;
    private javax.swing.JTextField txtcorreoacusuario;
    private javax.swing.JTextField txtcorreoausuario;
    private javax.swing.JTextField txtcorreoeusuario;
    private javax.swing.JTextField txtcorreorecargausuario;
    private javax.swing.JTextField txtdvausuario;
    private javax.swing.JTextField txtnombreacusuario;
    private javax.swing.JTextField txtnombreausuario;
    private javax.swing.JTextField txtnombreesaldo;
    private javax.swing.JTextField txtnombreeusuario;
    private javax.swing.JTextField txtnombrerecargausuario;
    private javax.swing.JTextField txtrecargausuario;
    private javax.swing.JTextField txtrutacusuario;
    private javax.swing.JTextField txtrutagregarusuario;
    private javax.swing.JTextField txtrutesaldousuario;
    private javax.swing.JTextField txtruteusuario;
    private javax.swing.JTextField txtrutsaldousuario;
    private javax.swing.JTextField txtsaldoausuario;
    // End of variables declaration//GEN-END:variables
}
